#!/bin/sh

SRC=$(cd `dirname $0` && pwd)

cat << EOF > $SRC/known.rs
// this file is auto-generated by gen-known.sh
use std::collections::HashSet;
use lazy_static::lazy_static;

lazy_static! {
    static ref BASE: HashSet<&'static str> = {
        let mut base = HashSet::new();
        // files from /usr/sbin
EOF
for BINARY in $(find /usr/sbin -type f | xargs realpath | sort); do
    PKG=$(dpkg -S $BINARY)
    echo "        base.insert(\"$BINARY\"); // $PKG" >> $SRC/known.rs
done
for BINARY in $(find /usr/bin -type f | xargs realpath | sort); do
    PKG=$(dpkg -S $BINARY)
    echo "        base.insert(\"$BINARY\"); // $PKG" >> $SRC/known.rs
done
cat << EOF >> $SRC/known.rs
        base
    }
}
EOF