// this file is almost auto-generated by gen-known.sh

use std::collections::HashSet;
use lazy_static::lazy_static;

lazy_static! {
    static ref BASE: HashSet<&'static str> = {
        let mut base = HashSet::new();
        base.insert("/usr/bin/["); // coreutils: /usr/bin/[
        base.insert("/usr/bin/aa-enabled"); // apparmor: /usr/bin/aa-enabled
        base.insert("/usr/bin/aa-exec"); // apparmor: /usr/bin/aa-exec
        base.insert("/usr/bin/aa-features-abi"); // apparmor: /usr/bin/aa-features-abi
        base.insert("/usr/bin/acpidbg"); // linux-tools-common: /usr/bin/acpidbg
        base.insert("/usr/bin/addpart"); // util-linux: /usr/bin/addpart
        base.insert("/usr/bin/apt"); // apt: /usr/bin/apt
        base.insert("/usr/bin/apt-cache"); // apt: /usr/bin/apt-cache
        base.insert("/usr/bin/apt-cdrom"); // apt: /usr/bin/apt-cdrom
        base.insert("/usr/bin/apt-config"); // apt: /usr/bin/apt-config
        base.insert("/usr/bin/apt-extracttemplates"); // apt-utils: /usr/bin/apt-extracttemplates
        base.insert("/usr/bin/apt-file"); // apt-file: /usr/bin/apt-file
        base.insert("/usr/bin/apt-ftparchive"); // apt-utils: /usr/bin/apt-ftparchive
        base.insert("/usr/bin/apt-get"); // apt: /usr/bin/apt-get
        base.insert("/usr/bin/apt-key"); // apt: /usr/bin/apt-key
        base.insert("/usr/bin/apt-mark"); // apt: /usr/bin/apt-mark
        base.insert("/usr/bin/apt-sortpkgs"); // apt-utils: /usr/bin/apt-sortpkgs
        base.insert("/usr/bin/arch"); // coreutils: /usr/bin/arch
        base.insert("/usr/bin/b2sum"); // coreutils: /usr/bin/b2sum
        base.insert("/usr/bin/base32"); // coreutils: /usr/bin/base32
        base.insert("/usr/bin/base64"); // coreutils: /usr/bin/base64
        base.insert("/usr/bin/basename"); // coreutils: /usr/bin/basename
        base.insert("/usr/bin/basenc"); // coreutils: /usr/bin/basenc
        base.insert("/usr/bin/bash"); // 
        base.insert("/usr/bin/bashbug"); // bash: /usr/bin/bashbug
        base.insert("/usr/bin/batch"); // at: /usr/bin/batch
        base.insert("/usr/bin/bootctl"); // systemd: /usr/bin/bootctl
        base.insert("/usr/bin/btrfs"); // 
        base.insert("/usr/bin/btrfs-convert"); // 
        base.insert("/usr/bin/btrfs-find-root"); // 
        base.insert("/usr/bin/btrfs-image"); // 
        base.insert("/usr/bin/btrfs-map-logical"); // 
        base.insert("/usr/bin/btrfs-select-super"); // 
        base.insert("/usr/bin/btrfstune"); // 
        base.insert("/usr/bin/bunzip2"); // 
        base.insert("/usr/bin/busctl"); // systemd: /usr/bin/busctl
        base.insert("/usr/bin/busybox"); // 
        base.insert("/usr/bin/byobu"); // byobu: /usr/bin/byobu
        base.insert("/usr/bin/byobu-config"); // byobu: /usr/bin/byobu-config
        base.insert("/usr/bin/byobu-ctrl-a"); // byobu: /usr/bin/byobu-ctrl-a
        base.insert("/usr/bin/byobu-disable"); // byobu: /usr/bin/byobu-disable
        base.insert("/usr/bin/byobu-disable-prompt"); // byobu: /usr/bin/byobu-disable-prompt
        base.insert("/usr/bin/byobu-enable"); // byobu: /usr/bin/byobu-enable
        base.insert("/usr/bin/byobu-enable-prompt"); // byobu: /usr/bin/byobu-enable-prompt
        base.insert("/usr/bin/byobu-export"); // byobu: /usr/bin/byobu-export
        base.insert("/usr/bin/byobu-janitor"); // byobu: /usr/bin/byobu-janitor
        base.insert("/usr/bin/byobu-keybindings"); // byobu: /usr/bin/byobu-keybindings
        base.insert("/usr/bin/byobu-launch"); // byobu: /usr/bin/byobu-launch
        base.insert("/usr/bin/byobu-launcher"); // byobu: /usr/bin/byobu-launcher
        base.insert("/usr/bin/byobu-launcher-install"); // byobu: /usr/bin/byobu-launcher-install
        base.insert("/usr/bin/byobu-launcher-uninstall"); // byobu: /usr/bin/byobu-launcher-uninstall
        base.insert("/usr/bin/byobu-layout"); // byobu: /usr/bin/byobu-layout
        base.insert("/usr/bin/byobu-prompt"); // byobu: /usr/bin/byobu-prompt
        base.insert("/usr/bin/byobu-quiet"); // byobu: /usr/bin/byobu-quiet
        base.insert("/usr/bin/byobu-reconnect-sockets"); // byobu: /usr/bin/byobu-reconnect-sockets
        base.insert("/usr/bin/byobu-select-backend"); // byobu: /usr/bin/byobu-select-backend
        base.insert("/usr/bin/byobu-select-profile"); // byobu: /usr/bin/byobu-select-profile
        base.insert("/usr/bin/byobu-select-session"); // byobu: /usr/bin/byobu-select-session
        base.insert("/usr/bin/byobu-shell"); // byobu: /usr/bin/byobu-shell
        base.insert("/usr/bin/byobu-silent"); // byobu: /usr/bin/byobu-silent
        base.insert("/usr/bin/byobu-status"); // byobu: /usr/bin/byobu-status
        base.insert("/usr/bin/byobu-status-detail"); // byobu: /usr/bin/byobu-status-detail
        base.insert("/usr/bin/byobu-ugraph"); // byobu: /usr/bin/byobu-ugraph
        base.insert("/usr/bin/byobu-ulevel"); // byobu: /usr/bin/byobu-ulevel
        base.insert("/usr/bin/bzcat"); // 
        base.insert("/usr/bin/bzdiff"); // 
        base.insert("/usr/bin/bzexe"); // 
        base.insert("/usr/bin/bzgrep"); // 
        base.insert("/usr/bin/bzip2"); // 
        base.insert("/usr/bin/bzip2recover"); // 
        base.insert("/usr/bin/bzmore"); // 
        base.insert("/usr/bin/cat"); // 
        base.insert("/usr/bin/catchsegv"); // libc-bin: /usr/bin/catchsegv
        base.insert("/usr/bin/catman"); // man-db: /usr/bin/catman
        base.insert("/usr/bin/cautious-launcher"); // mime-support: /usr/bin/cautious-launcher
        base.insert("/usr/bin/chattr"); // e2fsprogs: /usr/bin/chattr
        base.insert("/usr/bin/chcon"); // coreutils: /usr/bin/chcon
        base.insert("/usr/bin/check-language-support"); // language-selector-common: /usr/bin/check-language-support
        base.insert("/usr/bin/chronic"); // moreutils: /usr/bin/chronic
        base.insert("/usr/bin/ckbcomp"); // console-setup: /usr/bin/ckbcomp
        base.insert("/usr/bin/ckeygen3"); // python3-twisted: /usr/bin/ckeygen3
        base.insert("/usr/bin/cksum"); // coreutils: /usr/bin/cksum
        base.insert("/usr/bin/clear"); // ncurses-bin: /usr/bin/clear
        base.insert("/usr/bin/clear_console"); // bash: /usr/bin/clear_console
        base.insert("/usr/bin/cloud-id"); // cloud-init: /usr/bin/cloud-id
        base.insert("/usr/bin/cloud-init"); // cloud-init: /usr/bin/cloud-init
        base.insert("/usr/bin/cloud-init-per"); // cloud-init: /usr/bin/cloud-init-per
        base.insert("/usr/bin/cmake"); // cmake: /usr/bin/cmake
        base.insert("/usr/bin/cmp"); // diffutils: /usr/bin/cmp
        base.insert("/usr/bin/codepage"); // kbd: /usr/bin/codepage
        base.insert("/usr/bin/col1"); // byobu: /usr/bin/col1
        base.insert("/usr/bin/colrm"); // bsdextrautils: /usr/bin/colrm
        base.insert("/usr/bin/column"); // bsdextrautils: /usr/bin/column
        base.insert("/usr/bin/combine"); // moreutils: /usr/bin/combine
        base.insert("/usr/bin/comm"); // coreutils: /usr/bin/comm
        base.insert("/usr/bin/corelist"); // perl: /usr/bin/corelist
        base.insert("/usr/bin/cp"); // 
        base.insert("/usr/bin/cpack"); // cmake: /usr/bin/cpack
        base.insert("/usr/bin/cpan"); // perl: /usr/bin/cpan
        base.insert("/usr/bin/cpan5.30-aarch64-linux-gnu"); // libperl5.30:arm64: /usr/bin/cpan5.30-aarch64-linux-gnu
        base.insert("/usr/bin/cpio"); // 
        base.insert("/usr/bin/cpupower"); // linux-tools-common: /usr/bin/cpupower
        base.insert("/usr/bin/crontab"); // cron: /usr/bin/crontab
        base.insert("/usr/bin/csplit"); // coreutils: /usr/bin/csplit
        base.insert("/usr/bin/ctail"); // byobu: /usr/bin/ctail
        base.insert("/usr/bin/ctest"); // cmake: /usr/bin/ctest
        base.insert("/usr/bin/cut"); // coreutils: /usr/bin/cut
        base.insert("/usr/bin/dash"); // 
        base.insert("/usr/bin/date"); // 
        base.insert("/usr/bin/dbus-cleanup-sockets"); // dbus: /usr/bin/dbus-cleanup-sockets
        base.insert("/usr/bin/dbus-daemon"); // dbus: /usr/bin/dbus-daemon
        base.insert("/usr/bin/dbus-monitor"); // dbus: /usr/bin/dbus-monitor
        base.insert("/usr/bin/dbus-run-session"); // dbus: /usr/bin/dbus-run-session
        base.insert("/usr/bin/dbus-send"); // dbus: /usr/bin/dbus-send
        base.insert("/usr/bin/dbus-update-activation-environment"); // dbus: /usr/bin/dbus-update-activation-environment
        base.insert("/usr/bin/dbus-uuidgen"); // dbus: /usr/bin/dbus-uuidgen
        base.insert("/usr/bin/dd"); // 
        base.insert("/usr/bin/deallocvt"); // kbd: /usr/bin/deallocvt
        base.insert("/usr/bin/delpart"); // util-linux: /usr/bin/delpart
        base.insert("/usr/bin/df"); // 
        base.insert("/usr/bin/dfu-tool"); // fwupd: /usr/bin/dfu-tool
        base.insert("/usr/bin/dh_bash-completion"); // bash-completion: /usr/bin/dh_bash-completion
        base.insert("/usr/bin/diff"); // diffutils: /usr/bin/diff
        base.insert("/usr/bin/diff3"); // diffutils: /usr/bin/diff3
        base.insert("/usr/bin/dig"); // bind9-dnsutils: /usr/bin/dig
        base.insert("/usr/bin/dir"); // 
        base.insert("/usr/bin/dircolors"); // coreutils: /usr/bin/dircolors
        base.insert("/usr/bin/dirmngr-client"); // dirmngr: /usr/bin/dirmngr-client
        base.insert("/usr/bin/dirname"); // coreutils: /usr/bin/dirname
        base.insert("/usr/bin/dmesg"); // 
        base.insert("/usr/bin/do-release-upgrade"); // ubuntu-release-upgrader-core: /usr/bin/do-release-upgrade
        base.insert("/usr/bin/dpkg"); // dpkg: /usr/bin/dpkg
        base.insert("/usr/bin/dpkg-architecture"); // dpkg-dev: /usr/bin/dpkg-architecture
        base.insert("/usr/bin/dpkg-buildflags"); // dpkg-dev: /usr/bin/dpkg-buildflags
        base.insert("/usr/bin/dpkg-buildpackage"); // dpkg-dev: /usr/bin/dpkg-buildpackage
        base.insert("/usr/bin/dpkg-checkbuilddeps"); // dpkg-dev: /usr/bin/dpkg-checkbuilddeps
        base.insert("/usr/bin/dpkg-deb"); // dpkg: /usr/bin/dpkg-deb
        base.insert("/usr/bin/dpkg-distaddfile"); // dpkg-dev: /usr/bin/dpkg-distaddfile
        base.insert("/usr/bin/dpkg-divert"); // dpkg: /usr/bin/dpkg-divert
        base.insert("/usr/bin/dpkg-genbuildinfo"); // dpkg-dev: /usr/bin/dpkg-genbuildinfo
        base.insert("/usr/bin/dpkg-genchanges"); // dpkg-dev: /usr/bin/dpkg-genchanges
        base.insert("/usr/bin/dpkg-gencontrol"); // dpkg-dev: /usr/bin/dpkg-gencontrol
        base.insert("/usr/bin/dpkg-gensymbols"); // dpkg-dev: /usr/bin/dpkg-gensymbols
        base.insert("/usr/bin/dpkg-maintscript-helper"); // dpkg: /usr/bin/dpkg-maintscript-helper
        base.insert("/usr/bin/dpkg-mergechangelogs"); // dpkg-dev: /usr/bin/dpkg-mergechangelogs
        base.insert("/usr/bin/dpkg-name"); // dpkg-dev: /usr/bin/dpkg-name
        base.insert("/usr/bin/dpkg-parsechangelog"); // dpkg-dev: /usr/bin/dpkg-parsechangelog
        base.insert("/usr/bin/dpkg-query"); // dpkg: /usr/bin/dpkg-query
        base.insert("/usr/bin/dpkg-realpath"); // dpkg: /usr/bin/dpkg-realpath
        base.insert("/usr/bin/dpkg-scanpackages"); // dpkg-dev: /usr/bin/dpkg-scanpackages
        base.insert("/usr/bin/dpkg-scansources"); // dpkg-dev: /usr/bin/dpkg-scansources
        base.insert("/usr/bin/dpkg-shlibdeps"); // dpkg-dev: /usr/bin/dpkg-shlibdeps
        base.insert("/usr/bin/dpkg-source"); // dpkg-dev: /usr/bin/dpkg-source
        base.insert("/usr/bin/dpkg-split"); // dpkg: /usr/bin/dpkg-split
        base.insert("/usr/bin/dpkg-statoverride"); // dpkg: /usr/bin/dpkg-statoverride
        base.insert("/usr/bin/dpkg-trigger"); // dpkg: /usr/bin/dpkg-trigger
        base.insert("/usr/bin/dpkg-vendor"); // dpkg-dev: /usr/bin/dpkg-vendor
        base.insert("/usr/bin/du"); // coreutils: /usr/bin/du
        base.insert("/usr/bin/eatmydata"); // eatmydata: /usr/bin/eatmydata
        base.insert("/usr/bin/ec2metadata"); // cloud-guest-utils: /usr/bin/ec2metadata
        base.insert("/usr/bin/echo"); // 
        base.insert("/usr/bin/ed"); // 
        base.insert("/usr/bin/egrep"); // 
        base.insert("/usr/bin/eject"); // eject: /usr/bin/eject
        base.insert("/usr/bin/enc2xs"); // perl: /usr/bin/enc2xs
        base.insert("/usr/bin/encguess"); // perl: /usr/bin/encguess
        base.insert("/usr/bin/env"); // coreutils: /usr/bin/env
        base.insert("/usr/bin/envsubst"); // gettext-base: /usr/bin/envsubst
        base.insert("/usr/bin/expiry"); // passwd: /usr/bin/expiry
        base.insert("/usr/bin/expr"); // coreutils: /usr/bin/expr
        base.insert("/usr/bin/factor"); // coreutils: /usr/bin/factor
        base.insert("/usr/bin/faillog"); // login: /usr/bin/faillog
        base.insert("/usr/bin/fallocate"); // util-linux: /usr/bin/fallocate
        base.insert("/usr/bin/false"); // 
        base.insert("/usr/bin/fgconsole"); // 
        base.insert("/usr/bin/fgrep"); // 
        base.insert("/usr/bin/file"); // file: /usr/bin/file
        base.insert("/usr/bin/finalrd"); // finalrd: /usr/bin/finalrd
        base.insert("/usr/bin/fincore"); // util-linux: /usr/bin/fincore
        base.insert("/usr/bin/find"); // findutils: /usr/bin/find
        base.insert("/usr/bin/findmnt"); // 
        base.insert("/usr/bin/flock"); // util-linux: /usr/bin/flock
        base.insert("/usr/bin/fmt"); // coreutils: /usr/bin/fmt
        base.insert("/usr/bin/fold"); // coreutils: /usr/bin/fold
        base.insert("/usr/bin/free"); // procps: /usr/bin/free
        base.insert("/usr/bin/funzip"); // unzip: /usr/bin/funzip
        base.insert("/usr/bin/fuser"); // 
        base.insert("/usr/bin/fusermount"); // 
        base.insert("/usr/bin/fwupdagent"); // fwupd: /usr/bin/fwupdagent
        base.insert("/usr/bin/fwupdate"); // fwupd: /usr/bin/fwupdate
        base.insert("/usr/bin/fwupdmgr"); // fwupd: /usr/bin/fwupdmgr
        base.insert("/usr/bin/fwupdtool"); // fwupd: /usr/bin/fwupdtool
        base.insert("/usr/bin/fwupdtpmevlog"); // fwupd: /usr/bin/fwupdtpmevlog
        base.insert("/usr/bin/gapplication"); // libglib2.0-bin: /usr/bin/gapplication
        base.insert("/usr/bin/gawk"); // gawk: /usr/bin/gawk
        base.insert("/usr/bin/gdbus"); // libglib2.0-bin: /usr/bin/gdbus
        base.insert("/usr/bin/gencat"); // libc-dev-bin: /usr/bin/gencat
        base.insert("/usr/bin/getconf"); // libc-bin: /usr/bin/getconf
        base.insert("/usr/bin/getent"); // libc-bin: /usr/bin/getent
        base.insert("/usr/bin/getkeycodes"); // kbd: /usr/bin/getkeycodes
        base.insert("/usr/bin/getopt"); // util-linux: /usr/bin/getopt
        base.insert("/usr/bin/gettext"); // gettext-base: /usr/bin/gettext
        base.insert("/usr/bin/gettext.sh"); // gettext-base: /usr/bin/gettext.sh
        base.insert("/usr/bin/gio"); // libglib2.0-bin: /usr/bin/gio
        base.insert("/usr/bin/gpasswd"); // passwd: /usr/bin/gpasswd
        base.insert("/usr/bin/grep"); // 
        base.insert("/usr/bin/gresource"); // libglib2.0-bin: /usr/bin/gresource
        base.insert("/usr/bin/groups"); // coreutils: /usr/bin/groups
        base.insert("/usr/bin/growpart"); // cloud-guest-utils: /usr/bin/growpart
        base.insert("/usr/bin/gsettings"); // libglib2.0-bin: /usr/bin/gsettings
        base.insert("/usr/bin/gunzip"); // 
        base.insert("/usr/bin/gzexe"); // 
        base.insert("/usr/bin/gzip"); // 
        base.insert("/usr/bin/head"); // coreutils: /usr/bin/head
        base.insert("/usr/bin/helpztags"); // vim-common: /usr/bin/helpztags
        base.insert("/usr/bin/hexdump"); // bsdextrautils: /usr/bin/hexdump
        base.insert("/usr/bin/host"); // bind9-host: /usr/bin/host
        base.insert("/usr/bin/hostid"); // coreutils: /usr/bin/hostid
        base.insert("/usr/bin/hostname"); // 
        base.insert("/usr/bin/hostnamectl"); // systemd: /usr/bin/hostnamectl
        base.insert("/usr/bin/hwe-support-status"); // update-manager-core: /usr/bin/hwe-support-status
        base.insert("/usr/bin/iconv"); // libc-bin: /usr/bin/iconv
        base.insert("/usr/bin/id"); // coreutils: /usr/bin/id
        base.insert("/usr/bin/ifdata"); // moreutils: /usr/bin/ifdata
        base.insert("/usr/bin/ifne"); // moreutils: /usr/bin/ifne
        base.insert("/usr/bin/info"); // info: /usr/bin/info
        base.insert("/usr/bin/infocmp"); // ncurses-bin: /usr/bin/infocmp
        base.insert("/usr/bin/install"); // coreutils: /usr/bin/install
        base.insert("/usr/bin/install-info"); // install-info: /usr/bin/install-info
        base.insert("/usr/bin/instmodsh"); // perl: /usr/bin/instmodsh
        base.insert("/usr/bin/ionice"); // util-linux: /usr/bin/ionice
        base.insert("/usr/bin/ipcmk"); // util-linux: /usr/bin/ipcmk
        base.insert("/usr/bin/ipcrm"); // util-linux: /usr/bin/ipcrm
        base.insert("/usr/bin/ipcs"); // util-linux: /usr/bin/ipcs
        base.insert("/usr/bin/isutf8"); // moreutils: /usr/bin/isutf8
        base.insert("/usr/bin/join"); // coreutils: /usr/bin/join
        base.insert("/usr/bin/journalctl"); // 
        base.insert("/usr/bin/kernel-install"); // systemd: /usr/bin/kernel-install
        base.insert("/usr/bin/kill"); // 
        base.insert("/usr/bin/killall"); // psmisc: /usr/bin/killall
        base.insert("/usr/bin/kmod"); // 
        base.insert("/usr/bin/kmodsign"); // sbsigntool: /usr/bin/kmodsign
        base.insert("/usr/bin/kwboot"); // u-boot-tools: /usr/bin/kwboot
        base.insert("/usr/bin/landscape-sysinfo"); // landscape-common: /usr/bin/landscape-sysinfo
        base.insert("/usr/bin/last"); // util-linux: /usr/bin/last
        base.insert("/usr/bin/lastlog"); // login: /usr/bin/lastlog
        base.insert("/usr/bin/lcf"); // ucf: /usr/bin/lcf
        base.insert("/usr/bin/lckdo"); // moreutils: /usr/bin/lckdo
        base.insert("/usr/bin/ldd"); // libc-bin: /usr/bin/ldd
        base.insert("/usr/bin/less"); // less: /usr/bin/less
        base.insert("/usr/bin/lessecho"); // less: /usr/bin/lessecho
        base.insert("/usr/bin/lesskey"); // less: /usr/bin/lesskey
        base.insert("/usr/bin/lesspipe"); // less: /usr/bin/lesspipe
        base.insert("/usr/bin/lexgrog"); // man-db: /usr/bin/lexgrog
        base.insert("/usr/bin/libnetcfg"); // perl: /usr/bin/libnetcfg
        base.insert("/usr/bin/link"); // coreutils: /usr/bin/link
        base.insert("/usr/bin/linux-check-removal"); // linux-base: /usr/bin/linux-check-removal
        base.insert("/usr/bin/linux-update-symlinks"); // linux-base: /usr/bin/linux-update-symlinks
        base.insert("/usr/bin/linux-version"); // linux-base: /usr/bin/linux-version
        base.insert("/usr/bin/ln"); // 
        base.insert("/usr/bin/lnstat"); // iproute2: /usr/bin/lnstat
        base.insert("/usr/bin/loadkeys"); // 
        base.insert("/usr/bin/loadunimap"); // kbd: /usr/bin/loadunimap
        base.insert("/usr/bin/locale"); // libc-bin: /usr/bin/locale
        base.insert("/usr/bin/locale-check"); // base-files: /usr/bin/locale-check
        base.insert("/usr/bin/localectl"); // systemd: /usr/bin/localectl
        base.insert("/usr/bin/localedef"); // libc-bin: /usr/bin/localedef
        base.insert("/usr/bin/logger"); // bsdutils: /usr/bin/logger
        base.insert("/usr/bin/loginctl"); // 
        base.insert("/usr/bin/logname"); // coreutils: /usr/bin/logname
        base.insert("/usr/bin/look"); // bsdextrautils: /usr/bin/look
        base.insert("/usr/bin/ls"); // 
        base.insert("/usr/bin/lsattr"); // e2fsprogs: /usr/bin/lsattr
        base.insert("/usr/bin/lsb_release"); // lsb-release: /usr/bin/lsb_release
        base.insert("/usr/bin/lsblk"); // 
        base.insert("/usr/bin/lscpu"); // util-linux: /usr/bin/lscpu
        base.insert("/usr/bin/lshw"); // lshw: /usr/bin/lshw
        base.insert("/usr/bin/lsinitramfs"); // initramfs-tools-core: /usr/bin/lsinitramfs
        base.insert("/usr/bin/lsipc"); // util-linux: /usr/bin/lsipc
        base.insert("/usr/bin/lslocks"); // util-linux: /usr/bin/lslocks
        base.insert("/usr/bin/lslogins"); // util-linux: /usr/bin/lslogins
        base.insert("/usr/bin/lsmem"); // util-linux: /usr/bin/lsmem
        base.insert("/usr/bin/lsns"); // util-linux: /usr/bin/lsns
        base.insert("/usr/bin/lsof"); // lsof: /usr/bin/lsof
        base.insert("/usr/bin/lspci"); // pciutils: /usr/bin/lspci
        base.insert("/usr/bin/lspgpot"); // gnupg-utils: /usr/bin/lspgpot
        base.insert("/usr/bin/lsusb"); // usbutils: /usr/bin/lsusb
        base.insert("/usr/bin/ltrace"); // ltrace: /usr/bin/ltrace
        base.insert("/usr/bin/lz4"); // lz4: /usr/bin/lz4
        base.insert("/usr/bin/lzmainfo"); // xz-utils: /usr/bin/lzmainfo
        base.insert("/usr/bin/man"); // man-db: /usr/bin/man
        base.insert("/usr/bin/man-recode"); // man-db: /usr/bin/man-recode
        base.insert("/usr/bin/mandb"); // man-db: /usr/bin/mandb
        base.insert("/usr/bin/manifest"); // byobu: /usr/bin/manifest
        base.insert("/usr/bin/manpath"); // man-db: /usr/bin/manpath
        base.insert("/usr/bin/mapscrn"); // kbd: /usr/bin/mapscrn
        base.insert("/usr/bin/mawk"); // mawk: /usr/bin/mawk
        base.insert("/usr/bin/mcookie"); // util-linux: /usr/bin/mcookie
        base.insert("/usr/bin/md5sum"); // coreutils: /usr/bin/md5sum
        base.insert("/usr/bin/mdig"); // bind9-dnsutils: /usr/bin/mdig
        base.insert("/usr/bin/mesg"); // util-linux: /usr/bin/mesg
        base.insert("/usr/bin/mispipe"); // moreutils: /usr/bin/mispipe
        base.insert("/usr/bin/mk_modmap"); // kbd: /usr/bin/mk_modmap
        base.insert("/usr/bin/mkdir"); // 
        base.insert("/usr/bin/mkenvimage"); // u-boot-tools: /usr/bin/mkenvimage
        base.insert("/usr/bin/mkfifo"); // coreutils: /usr/bin/mkfifo
        base.insert("/usr/bin/mkimage"); // u-boot-tools: /usr/bin/mkimage
        base.insert("/usr/bin/mknod"); // 
        base.insert("/usr/bin/mksquashfs"); // squashfs-tools: /usr/bin/mksquashfs
        base.insert("/usr/bin/mksunxiboot"); // u-boot-tools: /usr/bin/mksunxiboot
        base.insert("/usr/bin/mktemp"); // 
        base.insert("/usr/bin/mkzftree"); // genisoimage: /usr/bin/mkzftree
        base.insert("/usr/bin/more"); // 
        base.insert("/usr/bin/mount"); // 
        base.insert("/usr/bin/mountpoint"); // 
        base.insert("/usr/bin/mt-gnu"); // 
        base.insert("/usr/bin/mtrace"); // libc-dev-bin: /usr/bin/mtrace
        base.insert("/usr/bin/mv"); // 
        base.insert("/usr/bin/namei"); // util-linux: /usr/bin/namei
        base.insert("/usr/bin/nano"); // 
        base.insert("/usr/bin/nc.openbsd"); // 
        base.insert("/usr/bin/netkit-ftp"); // ftp: /usr/bin/netkit-ftp
        base.insert("/usr/bin/netstat"); // 
        base.insert("/usr/bin/networkctl"); // 
        base.insert("/usr/bin/networkd-dispatcher"); // networkd-dispatcher: /usr/bin/networkd-dispatcher
        base.insert("/usr/bin/newgrp"); // login: /usr/bin/newgrp
        base.insert("/usr/bin/ngettext"); // gettext-base: /usr/bin/ngettext
        base.insert("/usr/bin/nice"); // coreutils: /usr/bin/nice
        base.insert("/usr/bin/nl"); // coreutils: /usr/bin/nl
        base.insert("/usr/bin/nproc"); // coreutils: /usr/bin/nproc
        base.insert("/usr/bin/nroff"); // groff-base: /usr/bin/nroff
        base.insert("/usr/bin/nsenter"); // util-linux: /usr/bin/nsenter
        base.insert("/usr/bin/nslookup"); // bind9-dnsutils: /usr/bin/nslookup
        base.insert("/usr/bin/nsupdate"); // bind9-dnsutils: /usr/bin/nsupdate
        base.insert("/usr/bin/ntfs-3g"); // 
        base.insert("/usr/bin/ntfs-3g.probe"); // 
        base.insert("/usr/bin/ntfscat"); // 
        base.insert("/usr/bin/ntfscluster"); // 
        base.insert("/usr/bin/ntfscmp"); // 
        base.insert("/usr/bin/ntfsdecrypt"); // ntfs-3g: /usr/bin/ntfsdecrypt
        base.insert("/usr/bin/ntfsfallocate"); // 
        base.insert("/usr/bin/ntfsfix"); // 
        base.insert("/usr/bin/ntfsinfo"); // 
        base.insert("/usr/bin/ntfsls"); // 
        base.insert("/usr/bin/ntfsmove"); // 
        base.insert("/usr/bin/ntfsrecover"); // 
        base.insert("/usr/bin/ntfssecaudit"); // 
        base.insert("/usr/bin/ntfstruncate"); // 
        base.insert("/usr/bin/ntfsusermap"); // 
        base.insert("/usr/bin/ntfswipe"); // 
        base.insert("/usr/bin/numfmt"); // coreutils: /usr/bin/numfmt
        base.insert("/usr/bin/od"); // coreutils: /usr/bin/od
        base.insert("/usr/bin/openssl"); // openssl: /usr/bin/openssl
        base.insert("/usr/bin/openvt"); // 
        base.insert("/usr/bin/parallel"); // moreutils: /usr/bin/parallel
        base.insert("/usr/bin/partx"); // util-linux: /usr/bin/partx
        base.insert("/usr/bin/passwd"); // passwd: /usr/bin/passwd
        base.insert("/usr/bin/paste"); // coreutils: /usr/bin/paste
        base.insert("/usr/bin/pastebinit"); // pastebinit: /usr/bin/pastebinit
        base.insert("/usr/bin/patch"); // patch: /usr/bin/patch
        base.insert("/usr/bin/pathchk"); // coreutils: /usr/bin/pathchk
        base.insert("/usr/bin/pee"); // moreutils: /usr/bin/pee
        base.insert("/usr/bin/peekfd"); // psmisc: /usr/bin/peekfd
        base.insert("/usr/bin/pewtwo"); // pipenv: /usr/bin/pewtwo
        base.insert("/usr/bin/pgrep"); // procps: /usr/bin/pgrep
        base.insert("/usr/bin/pinky"); // coreutils: /usr/bin/pinky
        base.insert("/usr/bin/pkaction"); // policykit-1: /usr/bin/pkaction
        base.insert("/usr/bin/pkcheck"); // policykit-1: /usr/bin/pkcheck
        base.insert("/usr/bin/pkcon"); // packagekit-tools: /usr/bin/pkcon
        base.insert("/usr/bin/pkexec"); // policykit-1: /usr/bin/pkexec
        base.insert("/usr/bin/pkmon"); // packagekit-tools: /usr/bin/pkmon
        base.insert("/usr/bin/pkttyagent"); // policykit-1: /usr/bin/pkttyagent
        base.insert("/usr/bin/pldd"); // libc-bin: /usr/bin/pldd
        base.insert("/usr/bin/plymouth"); // 
        base.insert("/usr/bin/pmap"); // procps: /usr/bin/pmap
        base.insert("/usr/bin/pr"); // coreutils: /usr/bin/pr
        base.insert("/usr/bin/printenv"); // coreutils: /usr/bin/printenv
        base.insert("/usr/bin/printf"); // coreutils: /usr/bin/printf
        base.insert("/usr/bin/prlimit"); // util-linux: /usr/bin/prlimit
        base.insert("/usr/bin/ps"); // 
        base.insert("/usr/bin/psfxtable"); // kbd: /usr/bin/psfxtable
        base.insert("/usr/bin/ptx"); // coreutils: /usr/bin/ptx
        base.insert("/usr/bin/purge-old-kernels"); // byobu: /usr/bin/purge-old-kernels
        base.insert("/usr/bin/pwd"); // 
        base.insert("/usr/bin/rdma"); // iproute2: /usr/bin/rdma
        base.insert("/usr/bin/readlink"); // 
        base.insert("/usr/bin/realpath"); // coreutils: /usr/bin/realpath
        base.insert("/usr/bin/red"); // 
        base.insert("/usr/bin/renice"); // bsdutils: /usr/bin/renice
        base.insert("/usr/bin/rescan-scsi-bus.sh"); // sg3-utils: /usr/bin/rescan-scsi-bus.sh
        base.insert("/usr/bin/resizepart"); // util-linux: /usr/bin/resizepart
        base.insert("/usr/bin/resolvectl"); // systemd: /usr/bin/resolvectl
        base.insert("/usr/bin/rev"); // util-linux: /usr/bin/rev
        base.insert("/usr/bin/rgrep"); // grep: /usr/bin/rgrep
        base.insert("/usr/bin/rm"); // 
        base.insert("/usr/bin/rmdir"); // 
        base.insert("/usr/bin/routef"); // iproute2: /usr/bin/routef
        base.insert("/usr/bin/routel"); // iproute2: /usr/bin/routel
        base.insert("/usr/bin/rsync"); // rsync: /usr/bin/rsync
        base.insert("/usr/bin/rsync-ssl"); // rsync: /usr/bin/rsync-ssl
        base.insert("/usr/bin/run-mailcap"); // mime-support: /usr/bin/run-mailcap
        base.insert("/usr/bin/run-one"); // run-one: /usr/bin/run-one
        base.insert("/usr/bin/run-parts"); // 
        base.insert("/usr/bin/runcon"); // coreutils: /usr/bin/runcon
        base.insert("/usr/bin/savelog"); // debianutils: /usr/bin/savelog
        base.insert("/usr/bin/sbattach"); // sbsigntool: /usr/bin/sbattach
        base.insert("/usr/bin/sbkeysync"); // sbsigntool: /usr/bin/sbkeysync
        base.insert("/usr/bin/sbsiglist"); // sbsigntool: /usr/bin/sbsiglist
        base.insert("/usr/bin/sbsign"); // sbsigntool: /usr/bin/sbsign
        base.insert("/usr/bin/sbvarsign"); // sbsigntool: /usr/bin/sbvarsign
        base.insert("/usr/bin/sbverify"); // sbsigntool: /usr/bin/sbverify
        base.insert("/usr/bin/script"); // bsdutils: /usr/bin/script
        base.insert("/usr/bin/scriptlive"); // bsdutils: /usr/bin/scriptlive
        base.insert("/usr/bin/scriptreplay"); // bsdutils: /usr/bin/scriptreplay
        base.insert("/usr/bin/scsi_logging_level"); // sg3-utils: /usr/bin/scsi_logging_level
        base.insert("/usr/bin/scsi_mandat"); // sg3-utils: /usr/bin/scsi_mandat
        base.insert("/usr/bin/scsi_readcap"); // sg3-utils: /usr/bin/scsi_readcap
        base.insert("/usr/bin/scsi_ready"); // sg3-utils: /usr/bin/scsi_ready
        base.insert("/usr/bin/scsi_satl"); // sg3-utils: /usr/bin/scsi_satl
        base.insert("/usr/bin/scsi_start"); // sg3-utils: /usr/bin/scsi_start
        base.insert("/usr/bin/scsi_stop"); // sg3-utils: /usr/bin/scsi_stop
        base.insert("/usr/bin/scsi_temperature"); // sg3-utils: /usr/bin/scsi_temperature
        base.insert("/usr/bin/sdiff"); // diffutils: /usr/bin/sdiff
        base.insert("/usr/bin/sed"); // 
        base.insert("/usr/bin/select-editor"); // sensible-utils: /usr/bin/select-editor
        base.insert("/usr/bin/sensible-browser"); // sensible-utils: /usr/bin/sensible-browser
        base.insert("/usr/bin/sensible-editor"); // sensible-utils: /usr/bin/sensible-editor
        base.insert("/usr/bin/sensible-pager"); // sensible-utils: /usr/bin/sensible-pager
        base.insert("/usr/bin/seq"); // coreutils: /usr/bin/seq
        base.insert("/usr/bin/setarch"); // util-linux: /usr/bin/setarch
        base.insert("/usr/bin/setfont"); // 
        base.insert("/usr/bin/setkeycodes"); // kbd: /usr/bin/setkeycodes
        base.insert("/usr/bin/setlogcons"); // kbd: /usr/bin/setlogcons
        base.insert("/usr/bin/setmetamode"); // kbd: /usr/bin/setmetamode
        base.insert("/usr/bin/setpci"); // pciutils: /usr/bin/setpci
        base.insert("/usr/bin/setpriv"); // util-linux: /usr/bin/setpriv
        base.insert("/usr/bin/setsid"); // util-linux: /usr/bin/setsid
        base.insert("/usr/bin/setterm"); // util-linux: /usr/bin/setterm
        base.insert("/usr/bin/setupcon"); // 
        base.insert("/usr/bin/sg_bg_ctl"); // sg3-utils: /usr/bin/sg_bg_ctl
        base.insert("/usr/bin/sg_compare_and_write"); // sg3-utils: /usr/bin/sg_compare_and_write
        base.insert("/usr/bin/sg_copy_results"); // sg3-utils: /usr/bin/sg_copy_results
        base.insert("/usr/bin/sg_dd"); // sg3-utils: /usr/bin/sg_dd
        base.insert("/usr/bin/sg_decode_sense"); // sg3-utils: /usr/bin/sg_decode_sense
        base.insert("/usr/bin/sg_emc_trespass"); // sg3-utils: /usr/bin/sg_emc_trespass
        base.insert("/usr/bin/sg_format"); // sg3-utils: /usr/bin/sg_format
        base.insert("/usr/bin/sg_get_config"); // sg3-utils: /usr/bin/sg_get_config
        base.insert("/usr/bin/sg_get_elem_status"); // sg3-utils: /usr/bin/sg_get_elem_status
        base.insert("/usr/bin/sg_get_lba_status"); // sg3-utils: /usr/bin/sg_get_lba_status
        base.insert("/usr/bin/sg_ident"); // sg3-utils: /usr/bin/sg_ident
        base.insert("/usr/bin/sg_inq"); // sg3-utils: /usr/bin/sg_inq
        base.insert("/usr/bin/sg_logs"); // sg3-utils: /usr/bin/sg_logs
        base.insert("/usr/bin/sg_luns"); // sg3-utils: /usr/bin/sg_luns
        base.insert("/usr/bin/sg_map"); // sg3-utils: /usr/bin/sg_map
        base.insert("/usr/bin/sg_map26"); // sg3-utils: /usr/bin/sg_map26
        base.insert("/usr/bin/sg_modes"); // sg3-utils: /usr/bin/sg_modes
        base.insert("/usr/bin/sg_opcodes"); // sg3-utils: /usr/bin/sg_opcodes
        base.insert("/usr/bin/sg_persist"); // sg3-utils: /usr/bin/sg_persist
        base.insert("/usr/bin/sg_prevent"); // sg3-utils: /usr/bin/sg_prevent
        base.insert("/usr/bin/sg_raw"); // sg3-utils: /usr/bin/sg_raw
        base.insert("/usr/bin/sg_rbuf"); // sg3-utils: /usr/bin/sg_rbuf
        base.insert("/usr/bin/sg_rdac"); // sg3-utils: /usr/bin/sg_rdac
        base.insert("/usr/bin/sg_read"); // sg3-utils: /usr/bin/sg_read
        base.insert("/usr/bin/sg_read_attr"); // sg3-utils: /usr/bin/sg_read_attr
        base.insert("/usr/bin/sg_read_block_limits"); // sg3-utils: /usr/bin/sg_read_block_limits
        base.insert("/usr/bin/sg_read_buffer"); // sg3-utils: /usr/bin/sg_read_buffer
        base.insert("/usr/bin/sg_read_long"); // sg3-utils: /usr/bin/sg_read_long
        base.insert("/usr/bin/sg_readcap"); // sg3-utils: /usr/bin/sg_readcap
        base.insert("/usr/bin/sg_reassign"); // sg3-utils: /usr/bin/sg_reassign
        base.insert("/usr/bin/sg_referrals"); // sg3-utils: /usr/bin/sg_referrals
        base.insert("/usr/bin/sg_rep_zones"); // sg3-utils: /usr/bin/sg_rep_zones
        base.insert("/usr/bin/sg_requests"); // sg3-utils: /usr/bin/sg_requests
        base.insert("/usr/bin/sg_reset"); // sg3-utils: /usr/bin/sg_reset
        base.insert("/usr/bin/sg_reset_wp"); // sg3-utils: /usr/bin/sg_reset_wp
        base.insert("/usr/bin/sg_rmsn"); // sg3-utils: /usr/bin/sg_rmsn
        base.insert("/usr/bin/sg_rtpg"); // sg3-utils: /usr/bin/sg_rtpg
        base.insert("/usr/bin/sg_safte"); // sg3-utils: /usr/bin/sg_safte
        base.insert("/usr/bin/sg_sanitize"); // sg3-utils: /usr/bin/sg_sanitize
        base.insert("/usr/bin/sg_sat_identify"); // sg3-utils: /usr/bin/sg_sat_identify
        base.insert("/usr/bin/sg_sat_phy_event"); // sg3-utils: /usr/bin/sg_sat_phy_event
        base.insert("/usr/bin/sg_sat_read_gplog"); // sg3-utils: /usr/bin/sg_sat_read_gplog
        base.insert("/usr/bin/sg_sat_set_features"); // sg3-utils: /usr/bin/sg_sat_set_features
        base.insert("/usr/bin/sg_scan"); // sg3-utils: /usr/bin/sg_scan
        base.insert("/usr/bin/sg_seek"); // sg3-utils: /usr/bin/sg_seek
        base.insert("/usr/bin/sg_senddiag"); // sg3-utils: /usr/bin/sg_senddiag
        base.insert("/usr/bin/sg_ses"); // sg3-utils: /usr/bin/sg_ses
        base.insert("/usr/bin/sg_ses_microcode"); // sg3-utils: /usr/bin/sg_ses_microcode
        base.insert("/usr/bin/sg_start"); // sg3-utils: /usr/bin/sg_start
        base.insert("/usr/bin/sg_stpg"); // sg3-utils: /usr/bin/sg_stpg
        base.insert("/usr/bin/sg_stream_ctl"); // sg3-utils: /usr/bin/sg_stream_ctl
        base.insert("/usr/bin/sg_sync"); // sg3-utils: /usr/bin/sg_sync
        base.insert("/usr/bin/sg_test_rwbuf"); // sg3-utils: /usr/bin/sg_test_rwbuf
        base.insert("/usr/bin/sg_timestamp"); // sg3-utils: /usr/bin/sg_timestamp
        base.insert("/usr/bin/sg_turs"); // sg3-utils: /usr/bin/sg_turs
        base.insert("/usr/bin/sg_unmap"); // sg3-utils: /usr/bin/sg_unmap
        base.insert("/usr/bin/sg_verify"); // sg3-utils: /usr/bin/sg_verify
        base.insert("/usr/bin/sg_vpd"); // sg3-utils: /usr/bin/sg_vpd
        base.insert("/usr/bin/sg_wr_mode"); // sg3-utils: /usr/bin/sg_wr_mode
        base.insert("/usr/bin/sg_write_buffer"); // sg3-utils: /usr/bin/sg_write_buffer
        base.insert("/usr/bin/sg_write_long"); // sg3-utils: /usr/bin/sg_write_long
        base.insert("/usr/bin/sg_write_same"); // sg3-utils: /usr/bin/sg_write_same
        base.insert("/usr/bin/sg_write_verify"); // sg3-utils: /usr/bin/sg_write_verify
        base.insert("/usr/bin/sg_write_x"); // sg3-utils: /usr/bin/sg_write_x
        base.insert("/usr/bin/sg_xcopy"); // sg3-utils: /usr/bin/sg_xcopy
        base.insert("/usr/bin/sg_zone"); // sg3-utils: /usr/bin/sg_zone
        base.insert("/usr/bin/sginfo"); // sg3-utils: /usr/bin/sginfo
        base.insert("/usr/bin/sgm_dd"); // sg3-utils: /usr/bin/sgm_dd
        base.insert("/usr/bin/sgp_dd"); // sg3-utils: /usr/bin/sgp_dd
        base.insert("/usr/bin/sha1sum"); // coreutils: /usr/bin/sha1sum
        base.insert("/usr/bin/sha224sum"); // coreutils: /usr/bin/sha224sum
        base.insert("/usr/bin/sha256sum"); // coreutils: /usr/bin/sha256sum
        base.insert("/usr/bin/sha384sum"); // coreutils: /usr/bin/sha384sum
        base.insert("/usr/bin/sha512sum"); // coreutils: /usr/bin/sha512sum
        base.insert("/usr/bin/showconsolefont"); // kbd: /usr/bin/showconsolefont
        base.insert("/usr/bin/showkey"); // kbd: /usr/bin/showkey
        base.insert("/usr/bin/shred"); // coreutils: /usr/bin/shred
        base.insert("/usr/bin/shuf"); // coreutils: /usr/bin/shuf
        base.insert("/usr/bin/skill"); // procps: /usr/bin/skill
        base.insert("/usr/bin/slabtop"); // procps: /usr/bin/slabtop
        base.insert("/usr/bin/sleep"); // 
        base.insert("/usr/bin/snap"); // snapd: /usr/bin/snap
        base.insert("/usr/bin/snapfuse"); // snapd: /usr/bin/snapfuse
        base.insert("/usr/bin/soelim"); // groff-base: /usr/bin/soelim
        base.insert("/usr/bin/sort"); // coreutils: /usr/bin/sort
        base.insert("/usr/bin/sotruss"); // libc-dev-bin: /usr/bin/sotruss
        base.insert("/usr/bin/splain"); // perl: /usr/bin/splain
        base.insert("/usr/bin/split"); // coreutils: /usr/bin/split
        base.insert("/usr/bin/splitfont"); // kbd: /usr/bin/splitfont
        base.insert("/usr/bin/sponge"); // moreutils: /usr/bin/sponge
        base.insert("/usr/bin/sprof"); // libc-dev-bin: /usr/bin/sprof
        base.insert("/usr/bin/ss"); // 
        base.insert("/usr/bin/ssh-add"); // openssh-client: /usr/bin/ssh-add
        base.insert("/usr/bin/ssh-agent"); // openssh-client: /usr/bin/ssh-agent
        base.insert("/usr/bin/ssh-argv0"); // openssh-client: /usr/bin/ssh-argv0
        base.insert("/usr/bin/ssh-copy-id"); // openssh-client: /usr/bin/ssh-copy-id
        base.insert("/usr/bin/ssh-import-id"); // ssh-import-id: /usr/bin/ssh-import-id
        base.insert("/usr/bin/ssh-import-id-gh"); // ssh-import-id: /usr/bin/ssh-import-id-gh
        base.insert("/usr/bin/ssh-import-id-lp"); // ssh-import-id: /usr/bin/ssh-import-id-lp
        base.insert("/usr/bin/ssh-keygen"); // openssh-client: /usr/bin/ssh-keygen
        base.insert("/usr/bin/ssh-keyscan"); // openssh-client: /usr/bin/ssh-keyscan
        base.insert("/usr/bin/stat"); // coreutils: /usr/bin/stat
        base.insert("/usr/bin/stdbuf"); // coreutils: /usr/bin/stdbuf
        base.insert("/usr/bin/stty"); // 
        base.insert("/usr/bin/sum"); // coreutils: /usr/bin/sum
        base.insert("/usr/bin/sync"); // 
        base.insert("/usr/bin/systemctl"); // 
        base.insert("/usr/bin/systemd-analyze"); // systemd: /usr/bin/systemd-analyze
        base.insert("/usr/bin/systemd-ask-password"); // 
        base.insert("/usr/bin/systemd-cat"); // systemd: /usr/bin/systemd-cat
        base.insert("/usr/bin/systemd-cgls"); // systemd: /usr/bin/systemd-cgls
        base.insert("/usr/bin/systemd-cgtop"); // systemd: /usr/bin/systemd-cgtop
        base.insert("/usr/bin/systemd-delta"); // systemd: /usr/bin/systemd-delta
        base.insert("/usr/bin/systemd-detect-virt"); // systemd: /usr/bin/systemd-detect-virt
        base.insert("/usr/bin/systemd-escape"); // 
        base.insert("/usr/bin/systemd-hwdb"); // 
        base.insert("/usr/bin/systemd-id128"); // systemd: /usr/bin/systemd-id128
        base.insert("/usr/bin/systemd-inhibit"); // 
        base.insert("/usr/bin/systemd-machine-id-setup"); // 
        base.insert("/usr/bin/systemd-mount"); // systemd: /usr/bin/systemd-mount
        base.insert("/usr/bin/systemd-notify"); // 
        base.insert("/usr/bin/systemd-path"); // systemd: /usr/bin/systemd-path
        base.insert("/usr/bin/systemd-run"); // systemd: /usr/bin/systemd-run
        base.insert("/usr/bin/systemd-socket-activate"); // systemd: /usr/bin/systemd-socket-activate
        base.insert("/usr/bin/systemd-stdio-bridge"); // systemd: /usr/bin/systemd-stdio-bridge
        base.insert("/usr/bin/systemd-sysusers"); // 
        base.insert("/usr/bin/systemd-tmpfiles"); // 
        base.insert("/usr/bin/systemd-tty-ask-password-agent"); // 
        base.insert("/usr/bin/tac"); // coreutils: /usr/bin/tac
        base.insert("/usr/bin/tail"); // coreutils: /usr/bin/tail
        base.insert("/usr/bin/tar"); // 
        base.insert("/usr/bin/taskset"); // util-linux: /usr/bin/taskset
        base.insert("/usr/bin/tbl"); // groff-base: /usr/bin/tbl
        base.insert("/usr/bin/tee"); // coreutils: /usr/bin/tee
        base.insert("/usr/bin/tempfile"); // 
        base.insert("/usr/bin/test"); // coreutils: /usr/bin/test
        base.insert("/usr/bin/time"); // time: /usr/bin/time
        base.insert("/usr/bin/timedatectl"); // systemd: /usr/bin/timedatectl
        base.insert("/usr/bin/timeout"); // coreutils: /usr/bin/timeout
        base.insert("/usr/bin/tload"); // procps: /usr/bin/tload
        base.insert("/usr/bin/top"); // procps: /usr/bin/top
        base.insert("/usr/bin/touch"); // 
        base.insert("/usr/bin/tr"); // coreutils: /usr/bin/tr
        base.insert("/usr/bin/true"); // 
        base.insert("/usr/bin/truncate"); // coreutils: /usr/bin/truncate
        base.insert("/usr/bin/ts"); // moreutils: /usr/bin/ts
        base.insert("/usr/bin/tsort"); // coreutils: /usr/bin/tsort
        base.insert("/usr/bin/tty"); // coreutils: /usr/bin/tty
        base.insert("/usr/bin/turbostat"); // linux-tools-common: /usr/bin/turbostat
        base.insert("/usr/bin/tzselect"); // libc-bin: /usr/bin/tzselect
        base.insert("/usr/bin/ubuntu-advantage"); // ubuntu-advantage-tools: /usr/bin/ubuntu-advantage
        base.insert("/usr/bin/ubuntu-security-status"); // update-manager-core: /usr/bin/ubuntu-security-status
        base.insert("/usr/bin/ucf"); // ucf: /usr/bin/ucf
        base.insert("/usr/bin/ucfq"); // ucf: /usr/bin/ucfq
        base.insert("/usr/bin/ucfr"); // ucf: /usr/bin/ucfr
        base.insert("/usr/bin/udevadm"); // 
        base.insert("/usr/bin/ul"); // bsdextrautils: /usr/bin/ul
        base.insert("/usr/bin/ulockmgr_server"); // 
        base.insert("/usr/bin/umount"); // 
        base.insert("/usr/bin/uname"); // 
        base.insert("/usr/bin/unattended-upgrade"); // unattended-upgrades: /usr/bin/unattended-upgrade
        base.insert("/usr/bin/uncompress"); // 
        base.insert("/usr/bin/unexpand"); // coreutils: /usr/bin/unexpand
        base.insert("/usr/bin/unicode_start"); // 
        base.insert("/usr/bin/unicode_stop"); // kbd: /usr/bin/unicode_stop
        base.insert("/usr/bin/uniq"); // coreutils: /usr/bin/uniq
        base.insert("/usr/bin/unlink"); // coreutils: /usr/bin/unlink
        base.insert("/usr/bin/unmkinitramfs"); // initramfs-tools-core: /usr/bin/unmkinitramfs
        base.insert("/usr/bin/unshare"); // util-linux: /usr/bin/unshare
        base.insert("/usr/bin/unsquashfs"); // squashfs-tools: /usr/bin/unsquashfs
        base.insert("/usr/bin/unzip"); // unzip: /usr/bin/unzip
        base.insert("/usr/bin/unzipsfx"); // unzip: /usr/bin/unzipsfx
        base.insert("/usr/bin/update-alternatives"); // dpkg: /usr/bin/update-alternatives
        base.insert("/usr/bin/update-mime-database"); // shared-mime-info: /usr/bin/update-mime-database
        base.insert("/usr/bin/uptime"); // procps: /usr/bin/uptime
        base.insert("/usr/bin/usb-devices"); // usbutils: /usr/bin/usb-devices
        base.insert("/usr/bin/usbhid-dump"); // usbutils: /usr/bin/usbhid-dump
        base.insert("/usr/bin/usbip"); // linux-tools-common: /usr/bin/usbip
        base.insert("/usr/bin/usbipd"); // linux-tools-common: /usr/bin/usbipd
        base.insert("/usr/bin/usbreset"); // usbutils: /usr/bin/usbreset
        base.insert("/usr/bin/users"); // coreutils: /usr/bin/users
        base.insert("/usr/bin/utmpdump"); // util-linux: /usr/bin/utmpdump
        base.insert("/usr/bin/uuidgen"); // uuid-runtime: /usr/bin/uuidgen
        base.insert("/usr/bin/uuidparse"); // uuid-runtime: /usr/bin/uuidparse
        base.insert("/usr/bin/vcs-run"); // cloud-guest-utils: /usr/bin/vcs-run
        base.insert("/usr/bin/vdir"); // 
        base.insert("/usr/bin/vidir"); // moreutils: /usr/bin/vidir
        base.insert("/usr/bin/vigpg"); // byobu: /usr/bin/vigpg
        base.insert("/usr/bin/vipe"); // moreutils: /usr/bin/vipe
        base.insert("/usr/bin/vmstat"); // procps: /usr/bin/vmstat
        base.insert("/usr/bin/w.procps"); // procps: /usr/bin/w.procps
        base.insert("/usr/bin/wall"); // bsdutils: /usr/bin/wall
        base.insert("/usr/bin/watch"); // procps: /usr/bin/watch
        base.insert("/usr/bin/wc"); // coreutils: /usr/bin/wc
        base.insert("/usr/bin/wdctl"); // 
        base.insert("/usr/bin/whatis"); // man-db: /usr/bin/whatis
        base.insert("/usr/bin/whereis"); // util-linux: /usr/bin/whereis
        base.insert("/usr/bin/which"); // debianutils: /usr/bin/which
        base.insert("/usr/bin/whiptail"); // whiptail: /usr/bin/whiptail
        base.insert("/usr/bin/who"); // coreutils: /usr/bin/who
        base.insert("/usr/bin/whoami"); // coreutils: /usr/bin/whoami
        base.insert("/usr/bin/write.ul"); // bsdextrautils: /usr/bin/write.ul
        base.insert("/usr/bin/xargs"); // findutils: /usr/bin/xargs
        base.insert("/usr/bin/xauth"); // xauth: /usr/bin/xauth
        base.insert("/usr/bin/xdg-user-dir"); // xdg-user-dirs: /usr/bin/xdg-user-dir
        base.insert("/usr/bin/xdg-user-dirs-update"); // xdg-user-dirs: /usr/bin/xdg-user-dirs-update
        base.insert("/usr/bin/xsubpp"); // perl: /usr/bin/xsubpp
        base.insert("/usr/bin/xxd"); // xxd: /usr/bin/xxd
        base.insert("/usr/bin/xz"); // xz-utils: /usr/bin/xz
        base.insert("/usr/bin/xzdiff"); // xz-utils: /usr/bin/xzdiff
        base.insert("/usr/bin/xzgrep"); // xz-utils: /usr/bin/xzgrep
        base.insert("/usr/bin/xzless"); // xz-utils: /usr/bin/xzless
        base.insert("/usr/bin/xzmore"); // xz-utils: /usr/bin/xzmore
        base.insert("/usr/bin/yes"); // coreutils: /usr/bin/yes
        base.insert("/usr/bin/zcat"); // 
        base.insert("/usr/bin/zcmp"); // 
        base.insert("/usr/bin/zdiff"); // 
        base.insert("/usr/bin/zdump"); // libc-bin: /usr/bin/zdump
        base.insert("/usr/bin/zegrep"); // 
        base.insert("/usr/bin/zfgrep"); // 
        base.insert("/usr/bin/zforce"); // 
        base.insert("/usr/bin/zgrep"); // 
        base.insert("/usr/bin/zipgrep"); // unzip: /usr/bin/zipgrep
        base.insert("/usr/bin/zipinfo"); // unzip: /usr/bin/zipinfo
        base.insert("/usr/bin/zless"); // 
        base.insert("/usr/bin/zmore"); // 
        base.insert("/usr/bin/znew"); // 
        base.insert("/usr/bin/zrun"); // moreutils: /usr/bin/zrun
        base
    };
}

pub fn is_base(binary: &str) -> bool {
    BASE.contains(binary)
}